# Generated by Django 3.2.3 on 2021-06-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='profile_pic',
            field=models.ImageField(default='', max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playgrounds',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
