# Generated by Django 3.2.3 on 2021-06-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20210605_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgrounds',
            name='address',
            field=models.CharField(default='Fayoum, el mesala', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playgrounds',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
