# Generated by Django 3.2.3 on 2021-06-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20210613_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='profile_pic',
            field=models.ImageField(default='', max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playgrounds',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
