# Generated by Django 3.2.3 on 2021-06-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20210613_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgrounds',
            name='address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playgrounds',
            name='description',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
