# Generated by Django 3.2.3 on 2021-06-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20210613_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgrounds',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
